### ISSUE TITLE
configuration.yaml

### ISSUE THREAD

**Issue by simonjowett** [DavidFW1960/bom-weather-card#27] opened 2020-09-18 02:13 UTC
Hi David - Firstly - brilliant piece of work!

Hello from a fellow Australian down here in Nowra.  I got your weather card fully working but all my code is in the configuration.yaml file - I couldn't get it working by having the weather.yaml file in a packages folder.  I kept getting an error "extra keys not allowed @ data['weather']"  I'm clearly having some formatting/naming issues.  I've carefully read and tried to research the issue but thought you might be able to offer a bit of guidance in your  readme about how to correctly point to the file from your configuration.yaml file.  Perhaps include a 'safe' copy of our own configuration.yaml (or a portion thereof).

Anyway thanks so much for a great visual treat on the HA platform. 
Cheers
Simon

**Comment by DavidFW1960** [comment] 2020-09-18 02:35
Thanks Simon.
My personal HA config is here https://github.com/DavidFW1960/home-assistant
I **suspect** you have not included packages in your configuration.yaml. Anyway check out my config and see. 
ALSO... this does not use the weather platform.. it's a sensor so if you have included any of my stuff under weather: that will be the issue.
If none of this helps, please post your weather.yaml package file and configuration.yaml so I can see what the problem is.

**Comment by simonjowett** [comment] 2020-09-18 03:45
ok - I'll do some more digging later.  I'm thinking your 2nd reason may be the case (I'm putting it under weather:)  Thanks for reponnding so quickly  - I will update

**Comment by DavidFW1960** [comment] 2020-09-18 05:20
Note as well I just edited the weather.yaml file to remove deprecated entity_id's

**Comment by DavidFW1960** [comment] 2020-09-23 00:20
I'll close this now.. assume it's fixed and working. Please post again if still having problems.

**Closed by DavidFW1960** 2020-09-23 00:20 UTC
