### ISSUE TITLE
Query: How to get card to work in HA 2021.6.2?

### ISSUE THREAD

**Issue by austwhite** [DavidFW1960/bom-weather-card#55] opened 2021-06-06 01:19 UTC
Good morning,

I have updated the BOM Weather Card via HACS to 0.89a this morning, but it seems the card still is not working for me.
I have logged this as a query rather than a fault as I am sure the issue could be my end.

I had the card working perfectly in HA 2021.5.x, but I still cannot get the card to display in 2021.6.x

Steps taken so far:
Updated card via HACS.
Updated HA to 2021.6.2
Checked Beta versions in HACS (same, 0.89a)
Restarted HA again.
Uninstalled BOM Weather Card via HACS
Reinstalled BOM Weather Card via HACS

I checked Home Assistant log file and I see this error:
*****
`http://homeassistant:8123/hacsfiles/bom-weather-card/bom-weather-card.js:914:14 Uncaught TypeError: Cannot read property 'childElementCount' of null`
11:10:23 AM - (ERROR) components/system_log/__init__.py
*****
Any tips would be appreciated.  I am sure there must be something simple I am missing.
Thanks

**Comment by DavidFW1960** [comment] 2021-06-06 01:34
Can you please check the other 2 issues that are identical to this one. My guess is that even if you updated via HACS that the old one is still cached. What version does the console say? Press F12 to check console. Should see:
Duplicate of #53

**Closed by DavidFW1960** 2021-06-06 01:34 UTC

**Comment by austwhite** [comment] 2021-06-06 01:36
Sorry.  Didn't see the other issues when I logged.  Will refresh and update an existing issue

**Comment by DavidFW1960** [comment] 2021-06-06 02:09
All good mate it just gets frustrating addressing the same thing over and over again and same issue on the forums as well - and same answer/resolution every time. I even pre-emptively fixed this before anyone should have even seen it and I still can't keep ahead of it lol....

**Comment by austwhite** [comment] 2021-06-06 02:15
It is definitely some.kind of weird caching issue in HA though.  Chrome, Edge and mobile all three the error and didn't update to the latest version, even with a ctrlF5 forced refresh.

Thanks for your help.  Clearing cache on Chrome fixed it.  Just got to wait for the mobile app as I can't be bothered clearing the cache on that

**Comment by DavidFW1960** [comment] 2021-06-06 02:29
Yeah I don't understand why it does this either but I always do the clear cache and hard reload every time HACS updates any custom-card and I check the version in the dev-tools as well and usually need to CTRL+R/F5 a few times cos for some reason it can jump back to the previous version as well... I do not understand why that's for sure.
There is a reset frontend cache in the mobile app and if you use that it will fix it for all mobile browsers as well..... As I use trusted networks and trusted users I don't even need to re-login on the app after I do this so it's worth doing and easy to do as well.
