### ISSUE TITLE
Migration of BOM baseline to NWS -- current issues 

### ISSUE THREAD

**Issue by Sudo-Rob** [DavidFW1960/bom-weather-card#66] opened 2021-12-19 21:39 UTC
Hi David.

As I posted, I'm currently migrating from DarkSky to NWS and using your weather card as one of choice.  It's mostly working.  Here's a current screen snippet:

![image](https://user-images.githubusercontent.com/56487711/146694745-68b7154a-3bce-48cb-8dbd-962a77c4b0f5.png)
![image](https://user-images.githubusercontent.com/56487711/146694130-87450046-6ea0-4390-b874-78559bea4d9a.png)

There are some obvious issue, but I'll address what I hope is the low-hanging fruit piecemeal.  Here are some configuration entries for the card:

1.  The value for atmospheric pressure has been truncated.  While the correct value was available, ...
![image](https://user-images.githubusercontent.com/56487711/146690138-bbbf4564-d5b1-4761-b187-a5d0527a469e.png)
...the value was rounded, snipping two significant digits.  Also, the units are wrong.  This could be an artifact of HA, so I've submitted a bug report (third of its kind; prior submittals were allowed to expire).

2. I've attempted to fill up the slots and keep the data aligned--specifically the `sun next` and `sun following` entries.  There are two visible issues: the absence of the `visibility` entry and/or the failure of the `empty` directive to leave an empty slot.  Here's the snapshot of the sensor:
![image](https://user-images.githubusercontent.com/56487711/146690701-35c2e1d1-43e5-458d-a3c7-37bc750310e5.png)
FYI, I've also attempted to replace the `visibility` sensor with `empty` (i.e., having two empties in successive slots), but that didn't realign `sun following` with `sun next`.

3. There's a missing prominent display of text near the top of the card for the current wx condition. In this case, I think it should be the one that selects the icon.  Am I making the wrong assumption?
![image](https://user-images.githubusercontent.com/56487711/146691203-0c952ef6-f208-43a0-a6b7-ad9a23803074.png)
![image](https://user-images.githubusercontent.com/56487711/146691164-9e879ec9-120c-49ba-aa87-752b67e85715.png)

I think the above is enough as a start.  There's some more, but I'd like some time to investigate how NWS condition entities are rendered to text and BOM icons. I might be able to sort that out without your help.

Thanks in advance.  Respectfully, Rob

**Comment by DavidFW1960** [comment] 2021-12-19 22:39
Hi Rob,

OK the pressure. Yes it rounds it to zero places but it uses the Locale to pick the text to display for your region. I can fix it so there is no rounding which shouldn't break anything else pretty easily. But if mbar is the correct pressure unit for your region I'd recommend using a template sensor to convert it to the correct units. If it doesn't suit you o do that you will need to edit the js file so that it uses the correct unit for you. If you are using HACS change the card version to Master, delete the .gz file  and edit this as follows: To remove the rounding on Line 453 delete math.round Thinking about this it only makes sense to show decimals if your unit is inHG. To change the units line 867 is the pressure units so you could edit the unit on that line by changing mbar to inHG.

I think you just deleted the lovelace config for the card... I need to see that.
I don't know why you can't use 2 empty slots adjacent to each other. maybe some way the css gets interpretted.
The current conditions uses a template sensor

**Comment by Sudo-Rob** [comment] 2021-12-19 23:14
Thanks for the reply.  Apologies.  I was editing when you answered.

The config for the slots is back.  Do you need the complete lovelace config?

I can easily edit the .js file, but would need to edit it after any update.  That said, if you're trying to make it more universal, having it follow the localization would be preferred.

I am using a template sensor to map the NWS data to your `entity_current_conditions`.  Shouldn't that be sufficient?  I think I bypassed the template, thinking putting the condition prior to the current forecast was superfluous if it was already at the top of the card.  Perhaps your template did more than I thought.

**Comment by Sudo-Rob** [comment] 2021-12-20 00:04
Well, that was easy enough, although your line numbers were off by +1.

![image](https://user-images.githubusercontent.com/56487711/146695342-896d869c-5fbb-42ef-b705-113d17e88300.png)

If you're wondering why there's no value for Today's high temperature, the NWS integration drops daily high when it's replaced by the current nightly low.  There is no "today's low", there's only daily high and nightly low in the NWS integration.  The only reason I have a daytime low is because my thermostat integration provides a DarkSky value.  I'll eventually have to do similar things for other values like UV indexes.

**Comment by DavidFW1960** [comment] 2021-12-20 02:18
BOM also drops off the high and low during the day so I use the average sensor on the actual read values and parse those to the card (the min and max)
You need both current conditions AND current text.
The localisation right now is merely checking if the length unit is Km and if it is then it will use mbar or hPA if the length unit is imperial. lines 866ff 
If the line number is different it's because HACS is downloading a different version as I haven't released a new one based on the Master yet. I had an error reported for the rounding that I have fixed but not released.
I'm open to changing the UOM or pressure but I have to consider who else is using it as is right now. I might ask on the forum for feedback on this.

**Comment by DavidFW1960** [comment] 2021-12-20 02:31
With the slots I suggest maybe moving one over from the left and leaving L5 and R5 empty?

**Comment by Sudo-Rob** [comment] 2021-12-20 03:01
Hmm...how can I do this?

I guess this is the template you use.  Correct?
>
      bom_current_text:
        value_template: >
            {% set val = states('sensor.kariong_short_text_0').split('.')[0] %} 
            {{ val | title }}
>
With what few template skills I have (still low on the learning curve), I'd need to use the state (reports `condition`) and look for keyword `forecast`[0] attribute.  Is this what your template does?  I only see one instance of `split` in the Jinja documentation, but it's in the context of a custom filter.  Not sure what it's doing.

Here is the entity, state, and first set of attributes:
![image](https://user-images.githubusercontent.com/56487711/146704546-3a011e76-a536-45c7-af96-7df7c0002268.png)

Thanks in advance.

**Comment by Sudo-Rob** [comment] 2021-12-20 07:45
Hi David,

I took another look at your forecast templates for the minimal card example and need to better understand how you're parsing them.  I also need to understand how an entity like `kariong_icon_descriptor_0` is generated.  Is it generated by the Bremor BOM component?  I suppose the most direct path to knowing would be to load the component and see what the entities look like.  It might have to wait for a while as I have some other obligations. 

Just to let you know, I started off by making my own templates using the information in the `weather.kbwi_daynight` entity.  The only thing remotely fancy in my value templates is separating min/max values and day/night forecasts by looking at the `daytime `attribute. The payloads for the weather card are either a single-number measurands, or a string for a forecast or icon.  These template values were presented to your minimum-configuration lovelace card as a starting point.  Min/max temperatures are properly time ordered and line up perfectly with tooltip daytime forecasts without resorting to `as_timestamp` conversion.

In the meantime I have a functional card. Your suggestions for the slots did not work as expected.  This is the closest I got, but it only worked with some value templates the integration could 'recognize.'

![image](https://user-images.githubusercontent.com/56487711/146729069-67a9fd94-cab2-4f33-9b43-477a84ce1242.png)

Thanks again.

**Comment by DavidFW1960** [comment] 2021-12-20 09:23
Hi rob. I'll take a look and explain tomorrow

**Comment by Sudo-Rob** [comment] 2021-12-20 17:08
FYI, I deleted l5 and r5 slots, and it still wouldn't line up the sun events.  There's something else going on, perhaps with the ones using multiple sensors.  For example, the rain and rain amount need both value templates present to properly populate the slot. 

Please don't feel pressured to reply straight away.  My attentions will be focused on holiday stuff over the next 10 days, or so, and I might not be able to reply.

Thanks!

**Comment by DavidFW1960** [comment] 2021-12-21 01:19
> Hi David,
> 
> I took another look at your forecast templates for the minimal card example and need to better understand how you're parsing them. I also need to understand how an entity like `kariong_icon_descriptor_0` is generated. Is it generated by the Bremor BOM component? I suppose the most direct path to knowing would be to load the component and see what the entities look like. It might have to wait for a while as I have some other obligations.

Ok Yes they come direct from the BOM Integration.

> 
> Just to let you know, I started off by making my own templates using the information in the `weather.kbwi_daynight` entity. The only thing remotely fancy in my value templates is separating min/max values and day/night forecasts by looking at the `daytime `attribute. The payloads for the weather card are either a single-number measurands, or a string for a forecast or icon. These template values were presented to your minimum-configuration lovelace card as a starting point. Min/max temperatures are properly time ordered and line up perfectly with tooltip daytime forecasts without resorting to `as_timestamp` conversion.
> 
I only use the as_timestamp in the template to set the bounds for the average sensor to read from midnight. (I think)

> In the meantime I have a functional card. Your suggestions for the slots did not work as expected. This is the closest I got, but it only worked with some value templates the integration could 'recognize.'
The chance of rain amount 
![image](https://user-images.githubusercontent.com/36390762/146853773-1b522a56-8765-488d-a321-3bbb9645846c.png)
is that an entity with any value? the N/A would indicate not.
it will use these 
```
entity_pop: sensor.kariong_rain_chance_0
entity_pop_intensity: sensor.gosford_rain_since_9am
entity_possible_today: sensor.kariong_rain_amount_range_0
```
and the slot config is
```
pop (probability of precipitation) Shows % possible rainfall today and the actual recorded rainfall
popforecast Shows % possible rainfall today and forecast rainfall
```
depending on which you want to show either forecast rain of recorded rain.
> 
> ![image](https://user-images.githubusercontent.com/56487711/146729069-67a9fd94-cab2-4f33-9b43-477a84ce1242.png)
> 
> Thanks again.
Regarding the empty slot.. I'm not sure why it's not working for you.
![image](https://user-images.githubusercontent.com/36390762/146854272-871fbb4b-5fe1-45e1-88b2-ad2d38596b1f.png)
See I set slot R3 to be empty and it is empty. Are you setting the slot value to empty or are you just not entering any text?

There's nothing at all special about using the BOM integration. As long as you are passing valid HA entities via the configuration they will show on the card.

I'm also thinking maybe I can fix the in/HG as well if I can test for the locale in JS. I'll see if I can do that

**Comment by Sudo-Rob** [comment] 2021-12-21 01:56
Hi again.

Thanks for the info.  

When I have the time, I'll load the BOM integration and make sure the values I use are compliant.  Unfortunately, the NWS data isn't as rich in content.  There are some things I've commented out.  Moreover, in the US, data are scattered between agencies.  It takes several API endpoints to accumulate the data provided the BOM.  The NWS hourly forecast might be able to provide enough data for some things like a nighttime high or a daytime low, but I'm not there yet.

I'll also look at the slot data to make sure the NWS templates look the same.  It might take some amount of learning to make a Jinja template do the same thing as the integration.

If I ever get things working well enough, I'll share the templates.

Once again, thanks.

R

**Comment by DavidFW1960** [comment] 2021-12-31 01:23
The windspeed will just be a number/string with no text. If it's ignoring it it's possible you have the wrong entity parsed. I think all HA states are actually strings.
The missing 5th day will be a problem for sure. It requires that. You could make a template sensor that gives a dummy value if it's missing in the integration and then parse those through to the card. so if it exists parse the correct number otherwise a dummy. The rain value uses either rain since 9am or a range of expected rain for the day. a template sensor could provide a better value than NaN for that as well.
The good thing about this card is it doesn't care how many sources you use... you are just parsing HA entities. But you need to make sure those entities exist and are parsing the correct data. Template sensors help with this particularly in your case. I can help with those if you can supply a screenshot of the HA dev-tools for what you have.

**Comment by Sudo-Rob** [comment] 2022-01-02 00:53
Thanks for the information.  Sorry for not responding sooner, but I was out of town for a bit.  I'll be getting back to the migration to NWS, hopefully over the next week.

**Comment by DavidFW1960** [comment] 2022-01-02 02:43
yeah. Template sensors will be your friend for this

**Comment by Sudo-Rob** [comment] 2022-01-06 16:13
I've looked at several strategies to determine how to handle the absence of daily forecasts.  This condition occurs regularly and fills up my log with errors.  So far, I've yet to come up with a workable solution.  I've tried tests such as using `is defined` to detect if a variable should be loaded with `None`.

The issue is once an indexed template variable is defined for a number of days, the absence of that variable generates an error before it can be evaluated.  The error is `UndefinedError: list object has no element xx`.

I think the next step might be to try to ingest daily forecasts with a `for` loop.  It'll be a learning experience, although I'm not sure doing so can generate template sensors on the fly using the loop index.

Any better ideas?

**Comment by DavidFW1960** [comment] 2022-01-06 22:49
I would be using a template to check the state. If the variable is gone it will be 'undefined' or something like that. You will need to check in states what HA is seeing when it's undefined and then pass an appropriate value to the card. An example of how I test day6 forecasts disappearing is in templates.md file for day6 forecast in the mini card I use....

**Comment by Sudo-Rob** [comment] 2022-01-06 23:26
Thanks for the reply. 

Perhaps I'm not making myself clear.  I still have a (mostly) functional weather card, but it's not being populated because the data aren't available.  For me, the issue I'm experiencing is ~30,000 lines of errors per day because NWS doesn't appear to provide stable service.  It's either that or the NWS integration is not reliably parsing the forecasts.  Somehow, I need to figure out what endpoint link is being used for my particular configuration.

I'll look at you templates.md file and see how you're doing it.  If it works to plug the deluge of errors, I'll be very happy.

**Comment by DavidFW1960** [comment] 2022-01-06 23:56
ok. 30000 lines of errors isn't fun

**Comment by Sudo-Rob** [comment] 2022-01-07 07:03
It seems I have a configuration issue.  I fired up another host and loaded it with HA.  The NWS integration works fine.  I'm going to let it run for day and see what happens.  I might use it to debug your weather card instead of my daily driver.

**Comment by DavidFW1960** [comment] 2022-01-08 07:06
If you pass valid entities and the required sensors it will work perfectly

**Comment by Sudo-Rob** [comment] 2022-01-08 16:25
No doubt.  I'm trying to figure out what to do with this and likely more:

![image](https://user-images.githubusercontent.com/56487711/148651312-9f57118b-953b-4c41-aa25-727158608b92.png)

I realize it's not the fault of the weather card integration, but I do need to determine what's going on with my HA instance before doing anything else.  It used to be rock solid.

Once again, thanks.

**Comment by DavidFW1960** [comment] 2022-01-09 03:57
yeah I can't help with that. I don't use that integration or have any knowledge of it

**Comment by Sudo-Rob** [comment] 2022-01-09 06:50
I removed your weather card integration and left the NWS integration keep running.  My Debian Supervised instance still drops the forecast every now and then--both for the 'daynight' and the 'hourly' forecasts.  When it drops, it's persistent; it doesn't recover.  Curiously, when it happens the current conditions are always present.

I think I need to figure out how to remove the NWS integration Docker container and reload it.  In contrast, the HA-OS instance is working correctly.

This is in the log:

`2022-01-09 00:37:42 ERROR (MainThread) [homeassistant.components.nws] Error requesting NWS forecast station kbwi data: 500, message='Internal Server Error', url=URL('https://api.weather.gov/gridpoints/LWX/101,88/forecast')
`

**Comment by DavidFW1960** [comment] 2022-01-09 08:36
Mine is not an integration. It's a custom card for displaying data from an integration. 
If the NWS integration sensor is available on HA start it shouldn't disappear if the data becomes unavailable. It should be able to recover.

**Comment by DavidFW1960** [comment] 2022-01-09 08:37
The current conditions is using a template isn't it? That could explain its persistence

**Comment by Sudo-Rob** [comment] 2022-01-09 17:57
Yes, it's a custom Lovelace card.  Apologies.

Currently, I'm only looking at the behavior of the NWS integration via the Entity, States, and Attributes presented in the Developer Tools.  All weather card configuration and resources have been removed or disabled to eliminate related template variables or other unknowns.  This is what I'm seeing at the moment:

![image](https://user-images.githubusercontent.com/56487711/148692173-b865f3ae-bcd7-4a03-a2a1-01d5a1fb642c.png)

Note there are no forecasts.  The endpoint link for the forecasts contains no current conditions, leading me to believe the  NWS entity must be using two or more endpoint links to assemble the attribute list.  Maybe I'll get inspired to look at the source code, but I'm getting impatient.

I've recently experienced issues (like, today) with the iOS companion app as well as NWS.  I'm starting to think I should bite the bullet and reintegrate the system from a fresh image.  Moreover, I'm considering migrating to HA OS (recently installed on a second host) and leaving Debian behind.

I'm sorry for this exercise.  I now know it has nothing to do with your custom card.  When I'm confident my system is working and stable, I'll revisit using the NWS integration with your card.

Respectfully.
R

**Comment by DavidFW1960** [comment] 2022-01-09 23:15
Even with the BOM custom integration the forecasts are a second set of sensors to the observations and the same information is also in a weather entity which could be accessed via templates but it's not necessary when you can just use the sensors. I also use a Debian supervised system. I would doubt this is your issue.

> I'm sorry for this exercise. I now know it has nothing to do with your custom card. When I'm confident my system is working and stable, I'll revisit using the NWS integration with your card.

yep. I think I'll close this issue for now.

**Closed by DavidFW1960** 2022-01-09 23:15 UTC

**Comment by Sudo-Rob** [comment] 2022-01-09 23:24
I doubt Debian is the issue, but I can see where the product is going.  If I knew where and how to look for the problem, the choice would be to stick with Debian.  I've reloaded the NWS integration multiple times.

Thanks for your patience.

**Comment by TheCranston** [comment] 2022-01-26 16:59
@Sudo-Rob I know the issue is closed (sorry for waking a dead issue David) but would love to work with you getting the card to work with NWS.  I have no way to reach you outside of your GitHub id. My profile has my email address.  Hopefully we can make a connection.
