### ISSUE TITLE
Layout Broken and/or new version not detected?

### ISSUE THREAD

**Issue by hastarin** [DavidFW1960/bom-weather-card#89] opened 2022-05-02 02:33 UTC
Apologies for creating this under the wrong project originally.

I've installed things via HACS and seem to be stuck on 0.94?

Layout appears fine in Chrome but in Edge the top elements are mis-aligned.

![image](https://user-images.githubusercontent.com/452393/166177344-0f0b7749-9771-4b16-9afd-d366c8639741.png)

```
type: custom:bom-weather-card
title: BOM Weather
entity_current_conditions: sensor.truganina_icon_descriptor_0
entity_temperature: sensor.laverton_temp
entity_daytime_high: sensor.truganina_temp_max_0
entity_daytime_low: sensor.truganina_temp_min_0
entity_forecast_high_temp_1: sensor.truganina_temp_max_1
entity_forecast_high_temp_2: sensor.truganina_temp_max_2
entity_forecast_high_temp_3: sensor.truganina_temp_max_3
entity_forecast_high_temp_4: sensor.truganina_temp_max_4
entity_forecast_high_temp_5: sensor.truganina_temp_max_5
entity_forecast_icon_1: sensor.truganina_icon_descriptor_1
entity_forecast_icon_2: sensor.truganina_icon_descriptor_2
entity_forecast_icon_3: sensor.truganina_icon_descriptor_3
entity_forecast_icon_4: sensor.truganina_icon_descriptor_4
entity_forecast_icon_5: sensor.truganina_icon_descriptor_5
entity_forecast_low_temp_1: sensor.truganina_temp_min_1
entity_forecast_low_temp_2: sensor.truganina_temp_min_2
entity_forecast_low_temp_3: sensor.truganina_temp_min_3
entity_forecast_low_temp_4: sensor.truganina_temp_min_4
entity_forecast_low_temp_5: sensor.truganina_temp_min_5
entity_summary_1: sensor.truganina_short_text_1
entity_summary_2: sensor.truganina_short_text_2
entity_summary_3: sensor.truganina_short_text_3
entity_summary_4: sensor.truganina_short_text_4
entity_summary_5: sensor.truganina_short_text_5
entity_sun: sun.sun
entity_wind_bearing: sensor.laverton_wind_direction
entity_wind_speed: sensor.laverton_wind_speed_kilometre
entity_wind_gust: sensor.laverton_gust_speed_kilometre
entity_humidity: sensor.netatmo_outdoor_humidity
entity_pressure: sensor.netatmo_indoor_pressure
entity_apparent_temp: sensor.laverton_temp_feels_like
entity_daily_summary: sensor.truganina_extended_text_0
entity_pop: sensor.truganina_rain_chance_0
entity_pop_intensity: sensor.laverton_rain_since_9am
entity_possible_today: sensor.truganina_rain_amount_range_0
entity_pos_1: sensor.truganina_rain_amount_range_1
entity_pos_2: sensor.truganina_rain_amount_range_2
entity_pos_3: sensor.truganina_rain_amount_range_3
entity_pos_4: sensor.truganina_rain_amount_range_4
entity_pos_5: sensor.truganina_rain_amount_range_5
entity_pop_1: sensor.truganina_rain_chance_1
entity_pop_2: sensor.truganina_rain_chance_2
entity_pop_3: sensor.truganina_rain_chance_3
entity_pop_4: sensor.truganina_rain_chance_4
entity_pop_5: sensor.truganina_rain_chance_5
locale: en
old_daily_format: false
old_icon: false
show_beaufort: false
static_icons: false
time_format: 24
tooltip_bg_color: rgb( 75,155,239)
tooltip_border_color: orange
tooltip_border_width: 3
tooltip_caret_size: 10
tooltip_fg_color: '#fff'
tooltip_left_offset: -12
tooltip_width: 100
tooltips: true
```

**Comment by markusg1234** [comment] 2022-05-02 02:47
Hi,
I have had this on my old android tablet for quite a while, but other tablets and computer browsers have been fine.

Yesterday this now has started on Edge with my main computer.

Regards,
Markus

**Comment by rudders** [comment] 2022-05-02 02:50
Seems like a "variations" class is the culprit if that helps debug.

![Screen Shot 2022-05-02 at 12 48 47 pm](https://user-images.githubusercontent.com/104969/166178644-c311209d-c528-4546-9d3e-08e4e2ef313c.png)

**Comment by DavidFW1960** [comment] 2022-05-02 02:55
0.94 is the latest. If you allow beta in HACs you can get the new version (not officially released yet) There is going to be another new version in a day or so that will be full config checking to help people setting the card up for the first time.

OK. So the display issues. You will find this is a browser issue. I have exactly the same issue with the Brave Browser. Chrome and edge seem OK and the iOS mobile app seems ok too.

Nothing really I can do about this that I can see. @Makin-Things Can you see anything we can do here?

What I did on the weekend was duplicate the card and use a custom state-switch card to display one version on my Desktop in Brave and the original version on the Mobile App. The Brave version in the card config I adjusted the css offsets:
```
temp_top_margin: -2.5em
temp_uom_top_margin: -7.25em
apparent_top_margin: -95px
current_text_top_margin: -50px
current_data_top_margin: 10em
large_icon_top_margin: -13.2em
```

**Comment by DavidFW1960** [comment] 2022-05-02 02:55
I think this is a browser update causing this BTW

**Comment by DavidFW1960** [comment] 2022-05-02 03:21
> Seems like a "variations" class is the culprit if that helps debug.
> 
> ![Screen Shot 2022-05-02 at 12 48 47 pm](https://user-images.githubusercontent.com/104969/166178644-c311209d-c528-4546-9d3e-08e4e2ef313c.png)

is that a new class Adrian?

**Comment by DavidFW1960** [comment] 2022-05-02 03:23
Seems to me it's applying that class to the slots whereas the issue seems to be with the stuff above there in the card.

**Comment by Makin-Things** [comment] 2022-05-02 03:24
Variations is the div that holds all the slots. It is not new.

**Comment by Makin-Things** [comment] 2022-05-02 03:24
I'll have a look a bit later. Just in the middle of something right now.

**Comment by DavidFW1960** [comment] 2022-05-02 03:30
> Variations is the div that holds all the slots. It is not new.

That's what I thought as well

**Comment by Makin-Things** [comment] 2022-05-02 03:36
This also looks similar to the issue I was seeing when testing HA Cast.

**Comment by jonwaland** [comment] 2022-05-02 05:44
just upgraded chrome (Version 101.0.4951.41 (Official Build) (32-bit) - WINDOWS) and getting same.

**Comment by Makin-Things** [comment] 2022-05-02 05:56
@jonwaland I also just updated and can confirm it is now broken. I will be looking into a fix asap now that I can easily reproduce the problem.

**Comment by Makin-Things** [comment] 2022-05-02 06:07
@DavidFW1960 PR created to hopefully fix it.

**Comment by DavidFW1960** [comment] 2022-05-02 06:27
Pr merged. Pull master folk. There is a major PR coming so might await that before making a new release.

**Comment by peterhoe** [comment] 2022-05-02 06:33
I get the same in home assistant companion app android 2022.3.0-full
![Screenshot_20220502-163051_Home Assistant](https://user-images.githubusercontent.com/36558013/166193823-3a6c27b7-66f2-458b-a4fb-ea829969365b.jpg)

**Comment by markusg1234** [comment] 2022-05-02 06:37
Thanks for the fix. All of my devices are now displaying correctly with master.

**Comment by Makin-Things** [comment] 2022-05-02 06:44
@peterhoe it took me a bit of effort to get the companion app to load the version from master, once it does reload it does in fact work for me at least (on android).

**Comment by DavidFW1960** [comment] 2022-05-02 07:17
Ok v1.03 just released to fix this

**Comment by peterhoe** [comment] 2022-05-02 08:15
> @peterhoe it took me a bit of effort to get the companion app to load the version from master, once it does reload it does in fact work for me at least (on android).

Thanks David & Makin-things Confirmed V1.03 fixes the issue.  Had to clear cache from Home assistant companion app, and re open app

For those looking, "clear cache" found on android for the Home assistant companion app can be foind at the following sub menus

settings / Apps / Home assistant / storage.  There are 2 options in there, choose "clear cache". (If you select "clear data", all configuration of the app will be lost and you start a fresh and have to reconfigure it - the app that is)

**Comment by hastarin** [comment] 2022-05-02 08:56
Thanks all. I can confirm that's fixed it for me.

I'm not sure if I should close the issue or leave that to a maintainer?

**Comment by Makin-Things** [comment] 2022-05-02 09:08
It's your issue. so feel free to close it if you the issue is solved, otherwise I am pretty sure @DavidFW1960 will close it otherwise in the near future.

**Comment by DavidFW1960** [comment] 2022-05-02 09:17
Just leave it open for now. Lots of people with the problem then hopefully see this instead of opening a new issue.

**Closed** 2022-05-04 02:08 UTC
